# Generated by Django 5.1.4 on 2025-05-21 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_hotel_room_monthlybill_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='monthlybill',
            name='generated_at',
        ),
    ]
